# Generated by Django 4.2.7 on 2023-11-07 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joke_id', models.IntegerField()),
                ('joke_category', models.CharField(max_length=100, verbose_name='Категория')),
                ('joke_start_data', models.DateTimeField(default=datetime.datetime(2023, 11, 7, 19, 34, 38, 916344), null=True, verbose_name='Дата создания')),
                ('joke_setup', models.CharField(max_length=200, verbose_name='Шутка')),
                ('joke_punchline', models.CharField(max_length=100, verbose_name='Ответ')),
            ],
        ),
    ]
